version: '3'
services:

  hotel-agent:
    image: registry.hub.docker.com/mydigiid/hotel-agent:latest
    container_name: hotel-agent
    ports:
      - 10080:10080
      - 10000:10000
    volumes:
      - ~/ssibk/.indy_client_hotel:/home/indy/.indy_client
    environment:
      - SSIBK_HOTEL_AGENT_IP_ADDRESS=${IP_ADDRESS}
      - SSIBK_HOTEL_AGENT_PORT_INBOUND=10000
      - SSIBK_HOTEL_AGENT_PORT_ADMIN=10080
      - SSIBK_HOTEL_AGENT_WEBHOOK_IP_ADDRESS=${IP_ADDRESS}
      - SSIBK_HOTEL_AGENT_WEBHOOK_PORT=8090
      - SSIBK_HOTEL_AGENT_API_KEY=${HOTEL_AGENT_API_KEY}
      - SSIBK_HOTEL_AGENT_SEED=000000000000000000000000000xxxxx
      - SSIBK_HOTEL_AGENT_WALLET_KEY=${HOTEL_AGENT_WALLET_KEY}
      - SSIBK_HOTEL_AGENT_WALLET_NAME=wallet
      - SSIBK_HOTEL_AGENT_NAME="TheHotel"
      - SSIBK_HOTEL_AGENT_LOG_LEVEL=info
      - SSIBK_HOTEL_AGENT_GENESIS_URL=${HOTEL_AGENT_GENESIS_URL}

  hotel-db:
    image: registry.hub.docker.com/mydigiid/hotel-db:latest
    container_name: hotel-db
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB-USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB-PASSWORD}
      - MONGO_INITDB_DATABASE=HotelController
      - CONTROLLER_DB_USERNAME=${CONTROLLER_DB_USERNAME}
      - CONTROLLER_DB_PASSWORD=${CONTROLLER_DB_PASSWORD}
    volumes:
      - ~/ssibk/hotel-db/:/data/db/

  smb-server:
    image: registry.hub.docker.com/mydigiid/smb-server:latest
    container_name: smb-server
    ports:
      - 2767:2767
    environment:
      - SSIBK_HOTEL_INTEGRATIONSERVICE_SMBSERVERCREDENTIALS_USERNAME=${SMBSERVERCREDENTIALS_USERNAME}
      - SSIBK_HOTEL_INTEGRATIONSERVICE_SMBSERVERCREDENTIALS_PASSWORD=${SMBSERVERCREDENTIALS_PASSWORD}
    volumes:
      - ~/ssibk/smb-server/:/data/smb-server/

  hotel-controller:
    image: registry.hub.docker.com/mydigiid/hotel-controller:latest
    container_name: hotel-controller
    ports:
      - 8090:8090
    depends_on:
      - hotel-db
      - hotel-agent
      - hotel-integrationservice
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SSIBK_HOTEL_CONTROLLER_ADMIN_USERNAME=${HOTEL_CONTROLLER_ADMIN_USERNAME}
      - SSIBK_HOTEL_CONTROLLER_ADMIN_PASSWORD=${HOTEL_CONTROLLER_ADMIN_PASSWORD}
      - SSIBK_HOTEL_CONTROLLER_AGENT_APIURL=http://${IP_ADDRESS}:10080
      - SSIBK_HOTEL_CONTROLLER_AGENT_APIKEY=${HOTEL_CONTROLLER_AGENT_APIKEY}
      - SSIBK_HOTEL_CONTROLLER_AGENT_ENDPOINT=http://${IP_ADDRESS}:10000
      - SSIBK_HOTEL_CONTROLLER_AGENT_ENDPOINT_NAME=IBM Hotel
      - SSIBK_HOTEL_CONTROLLER_AGENT_RECIPIENTKEY=${HOTEL_CONTROLLER_AGENT_RECIPIENTKEY}
      - SSIBK_HOTEL_CONTROLLER_AGENT_MASTERID_CREDENTIAL_DEFINITION_IDS=${HOTEL_AGENT_MASTERID_CREDENTIAL_DEFINITION_IDS}
      - SSIBK_HOTEL_CONTROLLER_AGENT_CORPORATEID_SCHEMA_IDS=${HOTEL_AGENT_CORPORATEID_SCHEMA_IDS}
      - SSIBK_HOTEL_CONTROLLER_AGENT_CORPORATEID_ISSUER_DIDS=${HOTEL_CONTROLLER_AGENT_CORPORATEID_ISSUER_DIDS}
      - SSIBK_HOTEL_CONTROLLER_INTEGRATIONSERVICE_APIURL=http://${IP_ADDRESS}:9081/api
      - SSIBK_HOTEL_CONTROLLER_INTEGRATIONSERVICE_APIKEY=${HOTEL_CONTROLLER_INTEGRATIONSERVICE_APIKEY}
      - SPRING_DATA_MONGODB_URI=mongodb://${MONGODB-USERNAME}:${MONGODB-PASSWORD}@${IP_ADDRESS}:27018/?authSource=HotelController
      - SPRING_DATA_MONGODB_DATABASE=HotelController

  hotel-integrationservice:
    image: registry.hub.docker.com/mydigiid/hotel-integrationservice:latest
    container_name: hotel-integrationservice
    ports:
      - 9081:9081
    environment:
      - SSIBK_HOTEL_INTEGRATIONSERVICE_APIKEY=${HOTEL_INTEGRATIONSERVICE_APIKEY}
      - SSIBK_HOTEL_INTEGRATIONSERVICE_SMBSERVERCREDENTIALS_USERNAME=${SMBSERVERCREDENTIALS_USERNAME}
      - SSIBK_HOTEL_INTEGRATIONSERVICE_SMBSERVERCREDENTIALS_PASSWORD=${SMBSERVERCREDENTIALS_PASSWORD}
      - SSIBK_HOTEL_INTEGRATIONSERVICE_SMBSERVERCREDENTIALS_SERVERNAME=${HOTEL_INTEGRATIONSERVICE_SMBSERVERCREDENTIALS_SERVERNAME}
      - SSIBK_HOTEL_INTEGRATIONSERVICE_SMBSERVERCREDENTIALS_PORT=139
      - SSIBK_HOTEL_INTEGRATIONSERVICE_SMBSERVERCREDENTIALS_FOLDER=${SMBSERVERCREDENTIALS_FOLDER}
      - SPRING_PROFILES_ACTIVE=dev
      - SIHOT_REST_ACTIONURL=${SIHOT_REST_ACTIONURL}
      - SIHOT_REST_ACTIONLOOKUPPATH=${SIHOT_REST_ACTIONLOOKUPPATH}
      - SIHOT_REST_ACTIONUPDATEPATH=${SIHOT_REST_ACTIONUPDATEPATH}
      - SIHOT_REST_AUTHHEADER=${SIHOT_REST_AUTHHEADER}
      - SIHOT_REST_BEONE=${SIHOT_REST_BEONE}
      - SIHOT_REST_PROFILETYPE=${SIHOT_REST_PROFILETYPE}
      - SIHOT_REST_GUESTTYPE=${SIHOT_REST_GUESTTYPE}
      - OPERA_ENDPOINTORIGIN_ENTITYID=${OPERA_ENDPOINTORIGIN_ENTITYID}
      - OPERA_ENDPOINTORIGIN_SYSTEMTYPE=${OPERA_ENDPOINTORIGIN_SYSTEMTYPE}
      - OPERA_ENDPOINTDESTINATION_ENTITYID=${OPERA_ENDPOINTDESTINATION_ENTITYID}
      - OPERA_ENDPOINTDESTINATION_SYSTEMTYPE=${OPERA_ENDPOINTDESTINATION_SYSTEMTYPE}
      - OPERA_USERNAME=${OPERA_USERNAME}
      - OPERA_PASSWORD=${OPERA_PASSWORD}
      - OPERA_DOMAIN=${OPERA_DOMAIN}
      - OPERA_TRANSACTIONID=${OPERA_TRANSACTIONID}
      - OPERA_DEFAULTURI_RESERVATION=${OPERA_DEFAULTURI_RESERVATION}
      - OPERA_DEFAULTURI_NAMECLIENT=${OPERA_DEFAULTURI_NAMECLIENT}
      - OPERA_SOAP_ACTION_BOOKING_SUMMARY=${OPERA_SOAP_ACTION_BOOKING_SUMMARY}
      - OPERA_SOAP_ACTION_FETCH_ADDRESS_LIST=${OPERA_SOAP_ACTION_FETCH_ADDRESS_LIST}
      - OPERA_SOAP_ACTION_UPDATE_ADDRESS=${OPERA_SOAP_ACTION_UPDATE_ADDRESS}
      - OPERA_SOAP_ACTION_UPDATE_NAME=${OPERA_SOAP_ACTION_UPDATE_NAME}
      - OPERA_TIMEOUT_CONNECTION_TIMEOUT= 60000
      - OPERA_TIMEOUT_READ_TIMEOUT= 60000

  hotel-ui:
    image: registry.hub.docker.com/mydigiid/hotel-ui:latest
    container_name: hotel-ui
    ports:
      - 3500:80
    depends_on:
      - hotel-controller
    environment:
      - SSIBK_HOTEL_UI_CONTROLLER_APIURL=http://${IP_ADDRESS}:8090
      - SSIBK_HOTEL_UI_LOGO_URL=https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/IBM_logo.svg/1000px-IBM_logo.svg.png
      - SSIBK_HOTEL_UI_TITLE=IBM Hotel